[2025-02-27T16:25:08.759+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-27T16:25:08.763+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: send_to_snowflake.fetch_data_from_url manual__2025-02-27T16:25:07.302343+00:00 [queued]>
[2025-02-27T16:25:08.766+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: send_to_snowflake.fetch_data_from_url manual__2025-02-27T16:25:07.302343+00:00 [queued]>
[2025-02-27T16:25:08.766+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 4
[2025-02-27T16:25:08.770+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): fetch_data_from_url> on 2025-02-27 16:25:07.302343+00:00
[2025-02-27T16:25:08.772+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=375) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-27T16:25:08.773+0000] {standard_task_runner.py:72} INFO - Started process 377 to run task
[2025-02-27T16:25:08.774+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'send_to_snowflake', 'fetch_data_from_url', 'manual__2025-02-27T16:25:07.302343+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/send_to_snowflakes.py', '--cfg-path', '/tmp/tmphs63qohj']
[2025-02-27T16:25:08.775+0000] {standard_task_runner.py:105} INFO - Job 11: Subtask fetch_data_from_url
[2025-02-27T16:25:08.791+0000] {task_command.py:467} INFO - Running <TaskInstance: send_to_snowflake.fetch_data_from_url manual__2025-02-27T16:25:07.302343+00:00 [running]> on host b80dd83948db
[2025-02-27T16:25:08.814+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='send_to_snowflake' AIRFLOW_CTX_TASK_ID='fetch_data_from_url' AIRFLOW_CTX_EXECUTION_DATE='2025-02-27T16:25:07.302343+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-27T16:25:07.302343+00:00'
[2025-02-27T16:25:08.815+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-27T16:25:09.146+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/send_to_snowflakes.py", line 54, in fetch_data_from_url
    context['ti'].xcom_push(key='raw_dataframe', value=fetch_data_from_url.to_json())
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'function' object has no attribute 'to_json'
[2025-02-27T16:25:09.153+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=send_to_snowflake, task_id=fetch_data_from_url, run_id=manual__2025-02-27T16:25:07.302343+00:00, execution_date=20250227T162507, start_date=20250227T162508, end_date=20250227T162509
[2025-02-27T16:25:09.160+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-27T16:25:09.160+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 11 for task fetch_data_from_url ('function' object has no attribute 'to_json'; 377)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/send_to_snowflakes.py", line 54, in fetch_data_from_url
    context['ti'].xcom_push(key='raw_dataframe', value=fetch_data_from_url.to_json())
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'function' object has no attribute 'to_json'
[2025-02-27T16:25:09.187+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2025-02-27T16:25:09.196+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-27T16:25:09.196+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
