[2025-02-27T17:04:17.250+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-27T17:04:17.256+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: send_to_snowflake.fetch_data_from_url manual__2025-02-27T17:04:16.225668+00:00 [queued]>
[2025-02-27T17:04:17.259+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: send_to_snowflake.fetch_data_from_url manual__2025-02-27T17:04:16.225668+00:00 [queued]>
[2025-02-27T17:04:17.259+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 4
[2025-02-27T17:04:17.264+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): fetch_data_from_url> on 2025-02-27 17:04:16.225668+00:00
[2025-02-27T17:04:17.271+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=207) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-27T17:04:17.272+0000] {standard_task_runner.py:72} INFO - Started process 209 to run task
[2025-02-27T17:04:17.271+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'send_to_snowflake', 'fetch_data_from_url', 'manual__2025-02-27T17:04:16.225668+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/send_to_snowflakes.py', '--cfg-path', '/tmp/tmpouynwxhz']
[2025-02-27T17:04:17.273+0000] {standard_task_runner.py:105} INFO - Job 48: Subtask fetch_data_from_url
[2025-02-27T17:04:17.309+0000] {task_command.py:467} INFO - Running <TaskInstance: send_to_snowflake.fetch_data_from_url manual__2025-02-27T17:04:16.225668+00:00 [running]> on host c26148b7476d
[2025-02-27T17:04:17.343+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='send_to_snowflake' AIRFLOW_CTX_TASK_ID='fetch_data_from_url' AIRFLOW_CTX_EXECUTION_DATE='2025-02-27T17:04:16.225668+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-27T17:04:16.225668+00:00'
[2025-02-27T17:04:17.344+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-27T17:04:17.603+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-27T17:04:17.606+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-27T17:04:17.606+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=send_to_snowflake, task_id=fetch_data_from_url, run_id=manual__2025-02-27T17:04:16.225668+00:00, execution_date=20250227T170416, start_date=20250227T170417, end_date=20250227T170417
[2025-02-27T17:04:17.631+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2025-02-27T17:04:17.639+0000] {taskinstance.py:3891} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-27T17:04:17.640+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
